### ISSUE TITLE
Brainstorm around the vocabulary and messaging

### ISSUE THREAD

**Issue by josecelano** [josecelano/library-consumer#4]
From this comment: https://github.com/josecelano/library-consumer/issues/2#issuecomment-1016425698

Define better wording and formats.

**Comment by josecelano** [comment]
This is how I see it right now.

I think we have a kind of N message queues each of them accepting only one message.

1. We receive the infrastructure event (the library has been updated)
2. We save the event (`library_aaa_was_updated`) in the event store (git database, commit object). We need to be sure we do not create duplicate events since we have parallel threads listening to Github events (schedule workflow that can be overlapped).
3. We have workers that process the events and we need an ACK system (another event) to indicate the events were processed.

In my previous version I wanted to create a json object representing the event inside the commit message:

```
{
  "name": "library_was_udpated",
  "version": 1,
  "payload": {
     "previous_ref": "...",
     "current_ref": "...",
     "submodule": "...",
     "submoudle_url": "...",
  },
  "metadata": {
     "runner_id": "..",
     "created_at": "..."
  }
}
```

Since we use json to pass data around we could use it in this case. We can mix it with a more human-friendly short description like the one we have now.

**Comment by josecelano** [comment]
As I mentioned [here](https://github.com/josecelano/library-consumer/pull/8#issuecomment-1018708566) I think the obvious implementation is:

Commit subject:

```
CLAIM LOCK: JOB: {QUEUE_NAME}
RELEASE LOCK: JOB DONE: {QUEUE_NAME}
```

Commit body:

```json
{
  "version": "1",
  "metadata": {
    ...
  },
  "payload": "escaped string with the user payload"
}
```

Where payload is whatever the queue user wants to store a message, for example:

```json
{
  "name": "",
  "version": "1",
  "data": {
    "previous_ref": "asfa8979sd7f",
    "current_ref": "asfa8979sd7f"
  } 
}
```

Regarding the commit subject maybe it makes sense to remove the reference to the lock:

Commit subject:

```
GIT-QUEUE: [NEW_JOB|JOB_DONE] - {QUEUE_NAME}
GIT-QUEUE: {MESSAGE_TYPE} - {QUEUE_NAME}
```

I don't like to include the job type, if we include it inside the commit body we could change the messages, which would make it a little bit slower to parse the git history. Because we have to read the commit body. On the other hand, this is not a generic message queue. It's only a job queue, so the messages types should not change, maybe only the attributes (which is possible using versions for the message types).

**Comment by josecelano** [comment]
Regarding the wording [this](https://github.com/josecelano/library-consumer/blob/issue-7-extract-gh-actions/.github/actions/git-queue/src/queue.ts) it's my proposal.

**Comment by yeraydavidrodriguez** [comment]
Great job @josecelano .

Regarding the wording, I really do think that we should use "lock" terminology. In my opinion, although it could be modeled as a queue, the ultimate reason for this is to avoid concurrency problems, so I think is better to use a concurrency-related terminology.

Also, I think that the suffixes should have the same length, in order to have a more easy to read history and avoid irregular margins.

Maybe something like:

```
🔒 LOCK REQUEST FOR JOB: XXX
🔓 LOCK RELEASE FOR JOB: XXX
```

**Comment by josecelano** [comment]
Hi @yeraydavidrodriguez thank you. I think we are not using "locks", at least not a "pessimistic" lock. In my first implementation, the "lock" commit prevented other workflows to start executing the job, but in this second implementation other workflows can pick up the same job. That's why I started changing the wording to queues. I think we have implemented:

- A job queue that can contain only one pending job at the same time.
- We allow more than 1 workflow to try to execute the job.
- Since we do not have a database to store the job state, we are using the git commit. And instead of changing the state, we write the new event. IT's like implementing event sourcing with git. We do not change the state of the job from _pending_ to _done_, we simply write a new event (job done).
- The "locking" or "concurrency" mechanism allows us to detect (optimistic locking) if we try to store a duplicate event (more than 1 pending job or marking a job as done twice).
- I think the "lock" is the git merge that detects changes already made in the "database" (git) when you try to write your changes.
- So I think the "commit" is the job and the git fast forward merge is the "lock" so the subject should reflect the job info.

Besides, we are planning to add one more event: "JOB STARTED" when the workflow starts processing the job. That event would not have any relation with the lock, right?

```text
GIT-QUEUE: {MESSAGE_TYPE} - {QUEUE_NAME}
GIT-QUEUE: NEW_JOB - {QUEUE_NAME}
GIT-QUEUE: START_JOB - {QUEUE_NAME}
GIT-QUEUE: END_JOB - {QUEUE_NAME}
```

Maybe we could even add the event version in the subject:

```text
GIT-QUEUE: {MESSAGE_TYPE}  - {MESSAGE_VERSION} - {QUEUE_NAME}
GIT-QUEUE: XXXXXXXXXXXXXXX - 01 - YYYYYYYYYYYYYYY
```

**Comment by da2ce7** [comment]
@josecelano

I like this naming scheme lots. :)

I think that the `Begin` and `Finish` words feel nice than `Start` and `End`.  We can use the Finish word here because we only merge if the job was completed successfully.

```
GIT-QUEUE: NEW_JOB - {QUEUE_NAME} -> [GIT PUSH]
GIT-QUEUE: BEGIN_JOB - {QUEUE_NAME}
GIT-QUEUE: FINISH_JOB - {QUEUE_NAME} -> [GIT PUSH]
```

The locking is done implicitly when the 'git push' command. Where non-ff merges are blocked.

---

If we want to optionally implement pessimistic locking into this system we could do the following:

Here the `Start` and `End` are better, as we will `End` the Exclusive period even if the job doesn't complete successfully.

Here we can use @yeraydavidrodriguez neat idea of using an emoji for the lock.

```
GIT-QUEUE: NEW_EXCLUSIVE_JOB - {QUEUE_NAME} -> [GIT PUSH]
GIT-QUEUE: 🔒 START_EXCLUSIVE_JOB - {QUEUE_NAME} -> [GIT PUSH]
GIT-QUEUE: 🔓 END_EXCLUSIVE_JOB - {QUEUE_NAME} -> [GIT PUSH]
```

**Comment by cgbosse** [comment]
@josecelano @da2ce7 @yeraydavidrodriguez 

Imagine for the optimistic another set of emojis.
:bowtie: = Begin  - The librarian
:fireworks: = Finish - Fireworks

**Comment by da2ce7** [comment]
> @josecelano @da2ce7 @yeraydavidrodriguez
> 
> Imagine for the optimistic another set of emojis. :bowtie: = Begin - The librarian 🎆 = Finish - Fireworks

If we are going to go all-out on emoji's then we could have:

```
GIT-QUEUE: 🈺 NEW_JOB
GIT-QUEUE: 👔 BEGIN_JOB
GIT-QUEUE: 🎆 FINISH_JOB

GIT-QUEUE: ⚙️ NEW_EXCLUSIVE_JOB
GIT-QUEUE: 🔒 START_EXCLUSIVE_JOB
GIT-QUEUE: 🔓 END_EXCLUSIVE_JOB
```

**Comment by cgbosse** [comment]
@da2ce7 
Sounds good to me.

**Comment by josecelano** [comment]
If we are going to go crazy with emojis:

```
📝📥 NEW_JOB
📝🔧 BEGIN_JOB
📝📤 FINISH_JOB

📝🚦 NEW_EXCLUSIVE_JOB
📝🔒 START_EXCLUSIVE_JOB
📝🔓 END_EXCLUSIVE_JOB
```

I did some tests:

![image](https://user-images.githubusercontent.com/58816/151165641-161c6e52-f5ab-4704-a4a9-d63d6e694fd4.png)

I'm not really sure if we should use emojis. My native language is Spanish and I learnt in the past that you should not use non-ASCII characters if you don't want unexpected behaviour. If we need more icons for new events in the future we can run of them. So we should make sure we are not going to need more.

**Comment by da2ce7** [comment]
> I'm not really sure if we should use emojis. My native language is Spanish and I learnt in the past that you should not use non-ASCII characters if you don't want unexpected behaviour. If we need more icons for new events in the future we can run of them. So we should make sure we are not going to need more.

Everything now is UTF-8.  Everything uses Unicode exclusivity now. - This is not a concern.

**Comment by josecelano** [comment]
hi @da2ce7 @cgbosse @yeraydavidrodriguez , this isthe summary from our previous meeting. Do you all agree?

### Commit subject

New job:

```text
📝: 🈺 {QUEUE_NAME} {JOB_NUMBER} {UNFINISHED_JOB_NUMBER}
📝: 🈺 my_queue 1 10
```

Created job commit: `0fdf0db843a2010702b7c8d2e446966e9302f40e`

Begin Job:

```text
📝: 👔 {QUEUE_NAME} {JOB_NUMBER} {UNFINISHED_JOB_NUMBER} {JOB_CREATION_COMMIT}
📝: 👔 my_queue 1 10 0fdf0db843a2010702b7c8d2e446966e9302f40e
```

Finish Job:

```text
📝: 👕 {QUEUE_NAME} {JOB_NUMBER} {UNFINISHED_JOB_NUMBER} {JOB_CREATION_COMMIT}
📝: 👕 my_queue 1 10 0fdf0db843a2010702b7c8d2e446966e9302f40e
```

Rules & notes:

- Delimiter is white space except for the second character `:`.
- `JOB_NUMBER`: is a job (not message) auto-incremental ID.
- `UNFINISHED_JOB_NUMBER`: is the number of unfinished jobs when the commit is created.
- `QUEUE_NAME`: is the name of the queue. Special characters or white spaces are replaced by  `-`.
- `JOB_CREATION_COMMIT`: the commit where the job was created.

### Commit body

CreateJobMessage:

```json
{
  "name": "create-job",
  "metadata": {
     "version": 1,
  }
  "payload": "{\"previous_ref\": \"...\",\n     \"current_ref\": \"...\",\n     \"submodule\": \"...\",\n     \"submoudle_url\": \"...\",\n}"
}
```

BeginJobMessage:

```json
{
  "name": "begin-job",
  "metadata": {
     "version": 1,
     "job_number": 1,
     "job_commit": "0fdf0db843a2010702b7c8d2e446966e9302f40e",
  },
  "payload": ""
}
```

FinishJobMessage:

```json
{
  "name": "finish-job",
  "metadata": {
     "version": 1,
     "job_number": 1,
     "job_commit": "0fdf0db843a2010702b7c8d2e446966e9302f40e",
  },
  "payload": ""
}
```

### Questions

- I think we should limit the size of the queue name to 30 characters, to make sure at least this message fits in 50 characters: `📝: 👔 my_queue_name_with_less_than30 10 100 872f40e`. Or even less if we expect more jobs.

**Comment by yeraydavidrodriguez** [comment]
Maybe it would make sense to put the ID / COUNT **before** the queue name?

Visually, it would make the history clearer. And I think it would be easier to process, especially if we allow numbers on the queue name.

**Comment by josecelano** [comment]
> Maybe it would make sense to put the ID / COUNT **before** the queue name?
> 
> Visually, it would make the history clearer. And I think it would be easier to process, especially if we allow numbers on the queue name.
> 
> Also, I put some extra characters to make the ID and Count more self-explanatory. Something like:
> 
> memo: u55b6 my_queue #1 (23) or memo: u55b6 my_queue 1/23
> 
> Seems easier to understand than just
> 
> memo: u55b6 my_queue 1 23
> 
> At the cost of more "noise" in the subject

I like the idea. I think we should be even more explicit because you do not know if that the total amount of jobs. Something like: `memo: u55b6 my_queue #1 (12/23)` where 12 is finished and 23 is the total.

**Comment by yeraydavidrodriguez** [comment]
Wow, it's very ugly how the emojis are re-written by github in the quoted text of previous comments (the paper-and-pencil emoji is replaced with the "memo" word, and the kanji with he "u55b6" code).

It seems that everyone handles the emojis like regular unicode characters.

**Comment by da2ce7** [comment]
After playing around with this idea a bit.
I think that when we make a new job we just say what the job number when we make a new one. It is implicit that it is one job higher than the last new job.

```
📝🈺: update_artwork: job.24
```

However, when we begin working on a job, we can say what it the current place in the queue, and reference the hash of the commit that defined this job:

```
📝👔: update_artwork: job.15/24: job.id.[NEW JOB HASH]
```

Then, when we finish/end the job, we can then reference the has of the comment where we signalled that we started working on it.

```
📝☑️: update_artwork: job.15/24: begin.id.[START/BEGIN JOB HASH]
```

Then there is a chain of hashes from the creation of the the job to it completion/end.

**Comment by josecelano** [comment]
Hi @da2ce7, I like the chain of hashes. 

I think the `id` can be mixed up with the job number. Should be better to use git wording like `ref`?:

```
📝👔: update_artwork: job.15/24: job.ref.[NEW JOB HASH]
```

**Comment by da2ce7** [comment]
Hello José,

Yes, the use of ‚ref‘ is more correct. 👍

:)

Cam.

**Comment by josecelano** [comment]
Moved to the action repo:

- https://github.com/Nautilus-Cyberneering/git-queue/issues/21
- https://github.com/Nautilus-Cyberneering/git-queue/issues/24
