### ISSUE TITLE
Choose a node package for git

### ISSUE THREAD

**Issue by josecelano** [josecelano/library-consumer#9]
Relates to: https://github.com/josecelano/library-consumer/issues/7

In order to implement the [get-active-lock.sh](https://github.com/josecelano/library-consumer/blob/main/scripts/get-active-lock.sh) script with `node` we need to use some git commands. We have to choose a node package for git.

For the time begin I've found these ones:

- [NodeGit](https://github.com/nodegit/nodegit)
- [Simple Git](https://github.com/steveukx/git-js)
- [isomorphic-git](https://github.com/isomorphic-git/isomorphic-git)

**Comment by da2ce7** [comment]
If we have a good version of Git supplied in the node execution environment, then perhaps https://github.com/steveukx/git-js (Simple Git), would be the best choice. As it has full TypeScript Bindings.

**Comment by josecelano** [comment]
### Basic info

| Feature | NodeGit | Simple Git | isomorphic-git |
| --- | --- | --- | --- |
| Contributors | 150 | 80 | 64 |
| Forks        | 678 | 257 | 269 |
| Starts       | 5.1k | 2.5k | 6.1k |
| Used by      | 4.5k | 87.6k | 1.9k |
| Sponsors     | NodeGit | Simple Git | isomorphic-git |

### Sponsors

NodeGit:

- [GitKraken](https://www.gitkraken.com/)
- [GitHub](https://github.com/)
- [bocoup](https://bocoup.com/)

### Website

- [NodeGit](https://www.nodegit.org/)
- [isomorphic-git](https://isomorphic-git.org/)

**Comment by josecelano** [comment]
I have [started using](https://github.com/josecelano/library-consumer/blob/issue-7-extract-gh-actions/.github/actions/git-queue/src/main.ts#L15) Simple Git. I like the TypeScript support too. I also prefer the async/await style. I do not see any major drawbacks. I have to check if we can sign commits. It seems it's possible because commands accept extra arguments.
